name: student
description: ABMTC student app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  mobile_scanner: ^1.1.0
  auto_route: ^5.0.1
  dartz: ^0.10.1
  responsive_framework: ^0.1.8
  flutter_native_splash: ^2.0.4
  injectable: ^1.5.3
  get_it: ^7.2.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.15
  flutter_platform_widgets: ^1.20.0
  image_picker: ^0.8.5+3
  parse_server_sdk_flutter: ^3.1.3
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  analyzer: ^4.3.0
  flutter_bloc: ^8.1.1
  sembast: ^3.3.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  skeletons: ^0.0.3
  line_awesome_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.1
  injectable_generator: ^1.5.3
  build_runner:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  freezed: ^2.0.4
  json_serializable: ^6.3.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/logo.png"
  image_path_ios: "assets/icon/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/illustrations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
