name: student
description: ABMTC student app.

publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  mobile_scanner: ^1.1.0
  auto_route: ^5.0.4
  dartz: ^0.10.1
  responsive_framework: ^0.2.0
  flutter_native_splash: ^2.2.16
  injectable: ^2.1.0
  get_it: ^7.2.0
  permission_handler: ^9.2.0
  flutter_platform_widgets: ^2.2.6
  image_picker: ^0.8.6+2
  parse_server_sdk_flutter: ^3.1.3
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  skeletons: ^0.0.3
  line_awesome_flutter: ^2.0.0
  google_nav_bar: ^5.0.6
  moment_dart: ^0.16.0
  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  build_runner: ^2.3.2
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.1
  json_serializable: ^6.5.4

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/adaptive_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/illustrations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
